### ISSUE TITLE
can't find file error in hearthstone mechanics

### ISSUE THREAD

**Issue by lishaodong** [lishaodong/Syndria#5]
[09:40:32] [Server thread/WARN]: java.io.IOException: No such file or directory
[09:40:32] [Server thread/WARN]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[09:40:32] [Server thread/WARN]: 	at java.io.File.createNewFile(File.java:1006)
[09:40:32] [Server thread/WARN]: 	at minecade.dungeonrealms.HearthstoneMechanics.HearthstoneMechanics.loadSpawnLocationTemplate(HearthstoneMechanics.java:383)
[09:40:32] [Server thread/WARN]: 	at minecade.dungeonrealms.HearthstoneMechanics.HearthstoneMechanics.onEnable(HearthstoneMechanics.java:67)
[09:40:32] [Server thread/WARN]: 	at minecade.dungeonrealms.Main.onEnable(Main.java:183)
[09:40:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[09:40:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[09:40:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[09:40:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
[09:40:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
[09:40:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
[09:40:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
[09:40:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
[09:40:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
[09:40:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
[09:40:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by lishaodong** [comment]
because the path of file is set in beginning.  static String templatePath_s=	Hive.rootDir+"/plugins/HearthstoneMechanics/spawn_locations.dat";

at that time. Hive.rootDir was not set.
